
--Xem danh sách sản phẩm
	CREATE OR ALTER PROCEDURE XEM_DS_SP
	AS 
		BEGIN TRAN
			SELECT *
			FROM SANPHAM
		COMMIT TRAN
	GO
--Tìm kiếm sản phẩm
	CREATE OR ALTER PROCEDURE TIM_SP
	(
		@TENSP NVARCHAR(50)
	)
	AS 
		BEGIN TRAN
			SELECT *
			FROM SANPHAM
			WHERE TenSP = @TENSP
		COMMIT TRAN
	GO
--Phân hệ khách hàng
	--Đặt hàng
	CREATE OR ALTER PROCEDURE KH_DAT_HANG
	(
		@MAHD NVARCHAR(10),
		@NGAYMUA DATE,
		@MADGHK NVARCHAR(10),
		@MAKH NVARCHAR(10),
		@TENSP NVARCHAR(50),
		@SOLUONG INT,
		@TENHTTT NVARCHAR(50),
		@DIACHIGIAOHANG NVARCHAR(150)
	)
	AS 
		BEGIN TRAN
			DECLARE @MAHTTT NVARCHAR(10)
			SET @MAHTTT = (SELECT MaHTTT FROM HTTHANHTOAN WHERE TenHTTT = @TENHTTT)
			DECLARE @MASP NVARCHAR(10)
			SET @MASP = (SELECT MaSP FROM SANPHAM WHERE TenSP = @TENSP)
			DECLARE @GIASP BIGINT
			SET @GIASP = (SELECT GiaSP FROM SANPHAM WHERE TenSP = @TENSP)
			--thêm mới hóa đơn
			INSERT INTO	HOADON VALUES
			(
				@MAHD,
				@NGAYMUA,
				NULL,
				N'Có',
				35000,
				@MAHTTT,
				NULL,
				@MAKH
			)
			--thêm mới chi tiết đơn hàng
			INSERT INTO CT_HOADON VALUES
			(
				@MAHD,
				@MASP,
				@SOLUONG,
				@SOLUONG * @GIASP
			)
			--thêm hóa đơn giao hàng
			INSERT INTO DONGH_KHACH VALUES
			(
				@MADGHK,
				@DIACHIGIAOHANG,
				N'Đang lấy hàng',
				@MAHD,
				NULL
			)
			DECLARE @SOLUONGTON INT
			SET @SOLUONGTON = (SELECT SoLuong FROM SANPHAM WHERE MaSP = @MASP)
			IF @SOLUONGTON > 0
			BEGIN	
				UPDATE SANPHAM SET SoLuong = @SOLUONGTON - @SOLUONG WHERE MaSP = @MASP
			END 
			ELSE 
			BEGIN 
				RAISERROR(N'Hết hàng',15,1)
				ROLLBACK
			END 
		COMMIT TRAN
	GO
	

--Phân hệ nhân viên
	--Lập hóa đơn
	CREATE OR ALTER PROCEDURE NV_LAP_HD
	(
		@MAHD NVARCHAR(10),
		@NGAYMUA DATE,
		@TENHTTT NVARCHAR(50),
		@MANV NVARCHAR(10),
		@MAKH NVARCHAR(10),
		@MASP NVARCHAR(10),
		@SOLUONG INT
	)
	AS 
		BEGIN TRAN
			DECLARE @MAHTTT NVARCHAR(10)
			SET @MAHTTT = (SELECT MaHTTT FROM HTTHANHTOAN WHERE TenHTTT = @TENHTTT)
			INSERT INTO HOADON VALUES 
			(
				@MAHD,
				@NGAYMUA,
				NULL,
				N'Không',
				0,
				@MAHTTT,
				@MANV,
				@MAKH
			)
			DECLARE @GIASP BIGINT
			SET @GIASP = (SELECT GiaSP FROM SANPHAM WHERE MaSP = @MASP)
			INSERT INTO CT_HOADON VALUES
			(
				@MAHD,
				@MASP,
				@SOLUONG,
				@SOLUONG * @GIASP
			)
			DECLARE @SOLUONGTON INT
			SET @SOLUONGTON = (SELECT SoLuong FROM SANPHAM WHERE MaSP = @MASP)
			IF @SOLUONGTON > 0
			BEGIN	
				UPDATE SANPHAM SET SoLuong = @SOLUONGTON - @SOLUONG WHERE MaSP = @MASP
			END 
			ELSE 
			BEGIN 
				RAISERROR(N'Hết hàng',15,1)
				ROLLBACK
			END 
		COMMIT TRAN
	GO

--Phân hệ nhân viên giao hàng
	--Tìm đơn giao hàng cho khách
	CREATE OR ALTER PROCEDURE NVGH_TIM_DONGH
	AS 
		BEGIN TRAN
			SELECT * FROM DONGH_KHACH
			WHERE MaNVGH IS NULL 
		COMMIT TRAN
	GO
	--Cập nhật tình trạng đơn hàng
	CREATE OR ALTER PROCEDURE NVGH_CAP_NHAT_DONGH
	(
		@MANVGH NVARCHAR(10),
		@MADGHK NVARCHAR(10),
		@TINHTRANGGIAO NVARCHAR(50)
	)
	AS 
		BEGIN TRAN
			UPDATE DONGH_KHACH SET TinhTrangGiao = @TINHTRANGGIAO 
							   WHERE MaDGHK = @MADGHK AND MaNVGH = @MANVGH
		COMMIT TRAN
	GO
	--Nhận đơn hàng online.
	CREATE OR ALTER PROCEDURE NVGH_NHAN_DONGH
	(
		@MANVGH NVARCHAR(10),
		@MADGHK NVARCHAR(10)
	)
	AS 
		BEGIN TRAN
			IF(SELECT MaNVGH FROM DONGH_KHACH WHERE  MaDGHK = @MADGHK)  IS NULL
			BEGIN	
				UPDATE DONGH_KHACH SET MaNVGH = @MANVGH WHERE MaDGHK = @MADGHK
			END 
			ELSE 
			BEGIN 
				RAISERROR(N'ĐƠN HÀNG ĐÃ ĐƯỢC NHẬN',15,1)
				ROLLBACK
			END 
		COMMIT TRAN
	GO

--Phân hệ quản trị
	--Xem thông tin nhân viên.
	CREATE OR ALTER PROCEDURE QT_XEM_NV
	AS 
		BEGIN TRAN
			SELECT *
			FROM NHANVIEN
		COMMIT TRAN
	GO
	--Thêm nhân viên
	CREATE OR ALTER PROCEDURE QT_THEM_NV
	(
		@MANV NVARCHAR(10),
		@TENNV NVARCHAR(50),
		@CMND NVARCHAR(15),
		@DIACHI NVARCHAR(150),
		@SODIENTHOAI NVARCHAR(15),
		@EMAIL NVARCHAR(50),
		@MACN NVARCHAR(10)
	)
	AS 
		BEGIN TRAN
			INSERT INTO NHANVIEN VALUES 
			(
				@MANV ,
				@TENNV ,
				@CMND ,
				@DIACHI ,
				@SODIENTHOAI ,
				@EMAIL ,
				@MACN 
			)
		COMMIT TRAN
	GO
	--Xóa nhân viên
	CREATE OR ALTER PROCEDURE QT_XOA_NV
	(
		@MANV NVARCHAR(10)
	)
	AS 
		BEGIN TRAN			
			DELETE FROM NHANVIEN WHERE MaNV = @MANV			
		COMMIT TRAN
	GO
	--Sửa nhân viên
	CREATE OR ALTER PROCEDURE QT_SUA_NV
	(
		@MANV NVARCHAR(10),
		@TENNV NVARCHAR(50),
		@CMND NVARCHAR(15),
		@DIACHI NVARCHAR(150),
		@SODIENTHOAI NVARCHAR(15),
		@EMAIL NVARCHAR(50),
		@MACN NVARCHAR(10)
	)
	AS 
		BEGIN TRAN
			UPDATE NHANVIEN SET TenNV = @TENNV, 
								CMND = @CMND, 
								DiaChi = @DIACHI,
								SoDienThoai = @SODIENTHOAI,
								Email = @EMAIL,
								MaCN = @MACN
							WHERE MaNV = @MANV
		COMMIT TRAN
	GO
	--Xem thông tin nhân viên giao hàng.
	CREATE OR ALTER PROCEDURE QT_XEM_NVGH
	AS 
		BEGIN TRAN
			SELECT *
			FROM NV_GIAOHANG
		COMMIT TRAN
	GO
	--Thêm nhân viên giao hàng
	CREATE OR ALTER PROCEDURE QT_THEM_NVGH
	(
		@MANVGH NVARCHAR(10),
		@TENNVGH NVARCHAR(50),
		@CMND NVARCHAR(15),
		@DIACHI NVARCHAR(150),
		@SODIENTHOAI NVARCHAR(15),
		@EMAIL NVARCHAR(50)
	)
	AS 
		BEGIN TRAN
			INSERT INTO NV_GIAOHANG VALUES 
			(
				@MANVGH ,
				@TENNVGH ,
				@CMND ,
				@DIACHI ,
				@SODIENTHOAI ,
				@EMAIL 
			)
		COMMIT TRAN
	GO
	--Xóa nhân viên giao hàng
	CREATE OR ALTER PROCEDURE QT_XOA_NVGH
	(
		@MANVGH NVARCHAR(10)
	)
	AS 
		BEGIN TRAN			
			DELETE FROM NV_GIAOHANG WHERE MaNVGH = @MANVGH			
		COMMIT TRAN
	GO

	--Sửa thông tin nhân viên giao hàng
	CREATE OR ALTER PROCEDURE QT_SUA_NVGH
	(
		@MANVGH NVARCHAR(10),
		@TENNVGH NVARCHAR(50),
		@CMND NVARCHAR(15),
		@DIACHI NVARCHAR(150),
		@SODIENTHOAI NVARCHAR(15),
		@EMAIL NVARCHAR(50)
	)
	AS 
		BEGIN TRAN
			UPDATE NV_GIAOHANG SET TenNVGH = @TENNVGH, 
									CMND = @CMND, 
									DiaChi = @DIACHI,
									SoDienThoai = @SODIENTHOAI,
									Email = @EMAIL
								WHERE MaNVGH = @MANVGH
		COMMIT TRAN
	GO
	--Xem sản phẩm.
	CREATE OR ALTER PROCEDURE QT_XEM_SP
	AS 
		BEGIN TRAN
			SELECT *
			FROM SANPHAM
		COMMIT TRAN
	GO
	--Thêm sản phẩm.
	CREATE OR ALTER PROCEDURE QT_THEM_SP
	(
		@MASP NVARCHAR(10),
		@TENSP NVARCHAR(50),
		@GIASP BIGINT,
		@SOLUONG INT,
		@MOTA NVARCHAR(150)
	)
	AS 
		BEGIN TRAN
			INSERT INTO SANPHAM VALUES 
			(
				@MASP,
				@TENSP,
				@GIASP,
				@SOLUONG,
				@MOTA
			)
		COMMIT TRAN
	GO
	--Xóa sản phẩm.
	CREATE OR ALTER PROCEDURE QT_XOA_SP
	(
		@MASP NVARCHAR(10)
	)
	AS 
		BEGIN TRAN			
			DELETE FROM SANPHAM WHERE MaSP = @MASP		
		COMMIT TRAN
	GO
	--Sửa sản phẩm.
	CREATE OR ALTER PROCEDURE QT_SUA_SP
	(
		@MASP NVARCHAR(10),
		@TENSP NVARCHAR(50),
		@GIASP BIGINT,
		@SOLUONG INT,
		@MOTA NVARCHAR(150)
	)
	AS 
		BEGIN TRAN
			UPDATE SANPHAM SET TenSP = @TENSP, 
								GiaSP = @GIASP, 
								SoLuong = @SOLUONG,
								MoTa = @MOTA
							WHERE MaSP = @MASP
		COMMIT TRAN
	GO
	--Xem chi nhánh.
	CREATE OR ALTER PROCEDURE QT_XEM_CN
	AS 
		BEGIN TRAN
			SELECT *
			FROM CHINHANH
		COMMIT TRAN
	GO
	--Thêm chi nhánh
	CREATE OR ALTER PROCEDURE QT_THEM_CN
	(
		@MACN NVARCHAR(10),
		@DIACHICN NVARCHAR(150),
		@SODIENTHOAI NVARCHAR(15)
	)
	AS 
		BEGIN TRAN
			INSERT INTO CHINHANH VALUES 
			(
				@MACN,
				@DIACHICN,
				@SODIENTHOAI
			)
		COMMIT TRAN
	GO
	--Xóa chi nhánh
	CREATE OR ALTER PROCEDURE QT_XOA_CN
	(
		@MACN NVARCHAR(10)
	)
	AS 
		BEGIN TRAN			
			DELETE FROM CHINHANH WHERE MaCN = @MACN		
		COMMIT TRAN
	GO
	--Sửa chi nhánh
	CREATE OR ALTER PROCEDURE QT_SUA_CN
	(
		@MACN NVARCHAR(10),
		@DIACHICN NVARCHAR(150),
		@SODIENTHOAI NVARCHAR(15)
	)
	AS 
		BEGIN TRAN
			UPDATE CHINHANH SET DiaChiCN = @DIACHICN,
								SoDienThoai = @SODIENTHOAI
							WHERE MaCN = @MACN
		COMMIT TRAN
	GO
	--Xem nhà cung cấp.
	CREATE OR ALTER PROCEDURE QT_XEM_NCC
	AS 
		BEGIN TRAN
			SELECT *
			FROM NHACUNGCAP
		COMMIT TRAN
	GO
	--Thêm nhà cung cấp
	CREATE OR ALTER PROCEDURE QT_THEM_NCC
	(
		@MANCC NVARCHAR(10),
		@TENNCC NVARCHAR(50),
		@DIACHINCC NVARCHAR(150),
		@SODIENTHOAI NVARCHAR(15)
	)
	AS 
		BEGIN TRAN
			INSERT INTO NHACUNGCAP VALUES 
			(
				@MANCC,
				@TENNCC,
				@DIACHINCC,
				@SODIENTHOAI
			)
		COMMIT TRAN
	GO
	--Xóa nhà cung cấp
	CREATE OR ALTER PROCEDURE QT_XOA_NCC
	(
		@MANCC NVARCHAR(10)
	)
	AS 
		BEGIN TRAN			
			DELETE FROM NHACUNGCAP WHERE MaNCC = @MANCC		
		COMMIT TRAN
	GO
	--Sửa nhà cung cấp
	CREATE OR ALTER PROCEDURE QT_THEM_NCC
	(
		@MANCC NVARCHAR(10),
		@TENNCC NVARCHAR(50),
		@DIACHINCC NVARCHAR(150),
		@SODIENTHOAI NVARCHAR(15)
	)
	AS 
		BEGIN TRAN
			UPDATE NHACUNGCAP SET TenNCC = @TENNCC,
									DiaChiNCC = @DIACHINCC,
									SoDienThoai = @SODIENTHOAI
							  WHERE MaNCC = @MANCC
		COMMIT TRAN
	GO
	--Xem phiếu đặt hàng.
	CREATE OR ALTER PROCEDURE QT_XEM_PHIEU_DH
	AS 
		BEGIN TRAN
			SELECT *
			FROM PHIEUDATHANG
		COMMIT TRAN
	GO
	--Thêm phiếu đặt hàng
	CREATE OR ALTER PROCEDURE QT_THEM_PHIEU_DH
	(
		@MAPDH NVARCHAR(10),
		@NGAYDATHANG DATE,
		@MANCC NVARCHAR(10),
		@MASP NVARCHAR(10),
		@SOLUONG INT,
		@GIA BIGINT
	)
	AS 
		BEGIN TRAN
			INSERT INTO PHIEUDATHANG VALUES 
			(
				@MAPDH,
				@NGAYDATHANG,
				@MANCC
			)
			INSERT INTO CT_PHIEUDATHANG VALUES
			(
				@MAPDH,
				@MASP,
				@SOLUONG,
				@GIA
			)
		COMMIT TRAN
	GO
	
	--Xem hình thức thanh toán.
	CREATE OR ALTER PROCEDURE QT_XEM_HTTT
	AS 
		BEGIN TRAN
			SELECT *
			FROM HTTHANHTOAN
		COMMIT TRAN
	GO
	--Thêm hình thức thanh toán.
	CREATE OR ALTER PROCEDURE QT_THEM_HTTT
	(
		@MAHTTT NVARCHAR(10),
		@TENHTTT NVARCHAR(50)
	)
	AS 
		BEGIN TRAN
			INSERT INTO HTTHANHTOAN VALUES 
			(
				@MAHTTT,
				@TENHTTT
			)
		COMMIT TRAN
	GO
	--Xóa hình thức thanh toán.
	CREATE OR ALTER PROCEDURE QT_XOA_HTTT
	(
		@MAHTTT NVARCHAR(10)
	)
	AS 
		BEGIN TRAN
			 DELETE FROM HTTHANHTOAN WHERE MaHTTT = @MAHTTT		
		COMMIT TRAN
	GO
	--Sửa hình thức thanh toán.
	CREATE OR ALTER PROCEDURE QT_SUA_HTTT
	(
		@MAHTTT NVARCHAR(10),
		@TENHTTT NVARCHAR(50)
	)
	AS 
		BEGIN TRAN
			UPDATE HTTHANHTOAN SET TenHTTT = @TENHTTT
								WHERE MaHTTT = @MAHTTT			
		COMMIT TRAN
	GO
	--Xem khách hàng.
	CREATE OR ALTER PROCEDURE QT_XEM_KH
	AS 
		BEGIN TRAN
			SELECT *
			FROM KHACHHANG
		COMMIT TRAN
	GO
	--Xóa khách hàng.
	CREATE OR ALTER PROCEDURE QT_XOA_KH
	(
		@MAKH NVARCHAR(10)
	)
	AS 
		BEGIN TRAN
			 DELETE FROM KHACHHANG WHERE MaKH = @MAKH
		COMMIT TRAN
	GO
	--Kiểm tra số lượng tồn sản phẩm.
	CREATE OR ALTER PROCEDURE QT_KIEM_TRA_SL
	(
		@SOLUONG INT
	)
	AS 
		BEGIN TRAN
			SELECT *
			FROM SANPHAM
			WHERE SoLuong < @SOLUONG 
		COMMIT TRAN
	GO

	