use ADB1_5_DATH2
go
----------------------------------------------------------------------
--Xem danh sách sản phẩm
CREATE OR ALTER PROCEDURE XEM_DS_SP
AS 
	BEGIN TRAN
		SELECT * FROM SANPHAM
	COMMIT TRAN
GO

--Tìm kiếm sản phẩm
CREATE OR ALTER PROCEDURE TIM_SP
(
	@TENSP NVARCHAR(50)
)
AS 
	BEGIN TRAN
		SELECT * FROM SANPHAM
		WHERE TenSP = @TENSP
	COMMIT TRAN
GO

--Nhân viên của chi nhánh
CREATE OR ALTER PROCEDURE NHANVIEN_CHINHANH
(
	@MACN INT
)
AS
	BEGIN TRAN
		SELECT MaNV		FROM NHANVIEN		WHERE MaCN = @MACN
	COMMIT TRAN
GO

--Phân hệ khách hàng
--Đặt hàng
CREATE OR ALTER PROCEDURE KH_DAT_HANG
(
	@NGAYMUA DATE,
	@MAKH INT,
	@TENHTTT NVARCHAR(50),
	@DIACHIGIAOHANG NVARCHAR(150)
)
AS 
	BEGIN TRAN
		DECLARE @MAHTTT NVARCHAR(10)
		SET @MAHTTT = (SELECT MaHTTT FROM HTTHANHTOAN WHERE TenHTTT = @TENHTTT)

		DECLARE @MAHD TABLE (HD INT)

		--thêm mới hóa đơn
		INSERT INTO	HOADON(NgayMua, YeuCauGiao, PhiVanChuyen, MaHTTT, MaNV, MaKH)
		OUTPUT inserted.MaHD into @MAHD
		VALUES (@NGAYMUA, N'Có', 35000, @MAHTTT, NULL, @MAKH)

		--thêm hóa đơn giao hàng
		INSERT INTO DONGH_KHACH(DiaChiGiaoHang, TinhTrangGiao, MaHD, MaNVGH)
		VALUES(@DIACHIGIAOHANG, N'Đang lấy hàng', (SELECT HD FROM @MAHD),NULL)
		(SELECT HD FROM @MAHD)
	COMMIT TRAN
GO

--Thêm chi tiết hóa đơn
CREATE OR ALTER PROCEDURE KH_DAT_HANG_CT
(
	@MAHD INT,
	@TENSP NVARCHAR(50),
	@SOLUONG INT
)
AS
	BEGIN TRAN
		DECLARE @MASP INT
		SET @MASP = (SELECT MaSP FROM SANPHAM WHERE TenSP = @TENSP)

		INSERT INTO CT_HOADON(MaHD, MaSP, SoLuong) VALUES(@MAHD, @MASP, @SOLUONG)

		DECLARE @SOLUONGTON INT
		SET @SOLUONGTON = (SELECT SoLuong FROM SANPHAM WHERE MaSP = @MASP)

		IF @SOLUONGTON > 0
		BEGIN	
			UPDATE SANPHAM SET SoLuong = @SOLUONGTON - @SOLUONG WHERE MaSP = @MASP
		END 
		ELSE 
		BEGIN 
			RAISERROR(N'Hết hàng', 15, 1)
			ROLLBACK
		END 

		SELECT *
		FROM CT_HOADON
		WHERE MaHD = @MAHD
	COMMIT TRAN
go

--Phân hệ nhân viên
--Lập hóa đơn
CREATE OR ALTER PROCEDURE NV_LAP_HD
(
	--@MAHD NVARCHAR(10),
	@NGAYLAP DATE,
	@TENHTTT NVARCHAR(50),
	@MANV INT,
	@MAKH INT
)
AS 
	BEGIN TRAN
		DECLARE @MAHTTT NVARCHAR(10)
		SET @MAHTTT = (SELECT MaHTTT FROM HTTHANHTOAN WHERE TenHTTT = @TENHTTT)

		DECLARE @MAHD TABLE (HD INT)

		INSERT INTO HOADON (NgayMua, YeuCauGiao, PhiVanChuyen, MaHTTT, MaNV, MaKH) 
		OUTPUT inserted.MaHD into @MAHD
		VALUES (@NGAYLAP,N'Không',0,@MAHTTT,@MANV,@MAKH)

		(SELECT HD FROM @MAHD)
	COMMIT TRAN
GO

--Thêm chi tiết hóa đơn
CREATE OR ALTER PROCEDURE NV_LAP_HD_CT
(
	@MAHD INT,
	@MASP INT,
	@SOLUONG INT
)
AS 
	BEGIN TRAN
		INSERT INTO CT_HOADON(MaHD, MaSP, SoLuong) 
		VALUES (@MAHD,@MASP,@SOLUONG)

		DECLARE @SOLUONGTON INT
		SET @SOLUONGTON = (SELECT SoLuong FROM SANPHAM WHERE MaSP = @MASP)
		IF @SOLUONGTON > 0
		BEGIN	
			UPDATE SANPHAM SET SoLuong = @SOLUONGTON - @SOLUONG WHERE MaSP = @MASP
		END 
		ELSE 
		BEGIN 
			RAISERROR(N'Hết hàng', 15, 1)
			ROLLBACK
		END 

		SELECT *
		FROM CT_HOADON
		WHERE MaHD = @MaHD
	COMMIT TRAN
GO

--Phân hệ nhân viên giao hàng
--Xem đơn hàng đã nhận
CREATE OR ALTER PROCEDURE NVGH_XEM_DONGH
(
	@MANVGH INT
)
AS
	BEGIN TRAN
		SELECT * FROM DONGH_KHACH WHERE MaNVGH = @MANVGH
	COMMIT TRAN
GO

--Tìm đơn giao hàng cho khách
CREATE OR ALTER PROCEDURE NVGH_TIM_DONGH
AS 
	BEGIN TRAN
		SELECT * FROM DONGH_KHACH
		WHERE MaNVGH IS NULL 
	COMMIT TRAN
GO

--Cập nhật tình trạng đơn hàng
CREATE OR ALTER PROCEDURE NVGH_CAP_NHAT_DONGH
(
	@MANVGH INT,
	@MADGHK INT,
	@TINHTRANGGIAO NVARCHAR(50)
)
AS 
	BEGIN TRAN
		UPDATE DONGH_KHACH 
		SET TinhTrangGiao = @TINHTRANGGIAO 
		WHERE MaDGHK = @MADGHK AND MaNVGH = @MANVGH
		
		SELECT *
		FROM DONGH_KHACH
		WHERE MaDGHK = @MADGHK AND MaNVGH = @MANVGH
	COMMIT TRAN
GO

--Nhận đơn hàng online.
CREATE OR ALTER PROCEDURE NVGH_NHAN_DONGH
(
	@MANVGH INT,
	@MADGHK INT
)
AS 
	BEGIN TRAN
		IF(SELECT MaNVGH FROM DONGH_KHACH WHERE MaDGHK = @MADGHK)  IS NULL
		BEGIN	
			UPDATE DONGH_KHACH SET MaNVGH = @MANVGH WHERE MaDGHK = @MADGHK
		END 
		ELSE 
		BEGIN 
			RAISERROR(N'Đơn hàng đã được nhận', 15, 1)
			ROLLBACK
		END 
	COMMIT TRAN
GO

--Phân hệ quản trị
--Xem thông tin nhân viên.
CREATE OR ALTER PROCEDURE QT_XEM_NV
AS 
	BEGIN TRAN
		SELECT * FROM NHANVIEN
	COMMIT TRAN
GO

--Thêm nhân viên
CREATE OR ALTER PROCEDURE QT_THEM_NV
(
	@TENNV NVARCHAR(50),
	@CMND NVARCHAR(15),
	@DIACHI NVARCHAR(150),
	@SODIENTHOAI CHAR(15),
	@EMAIL NVARCHAR(50),
	@MACN INT
)
AS 
BEGIN TRAN
	IF EXISTS (SELECT * FROM NHANVIEN WHERE CMND = @CMND)
	BEGIN
		RAISERROR (N'Chứng minh nhân dân đã tồn tại', 15, 1)
		ROLLBACK TRAN
	END

	ELSE 
	BEGIN
		IF EXISTS (SELECT * FROM NHANVIEN WHERE SoDienThoai = @SODIENTHOAI)
		BEGIN
			RAISERROR (N'Số điện thoại đã tồn tại', 15, 1)
			ROLLBACK TRAN
		END
		ELSE 
		BEGIN
			INSERT INTO NHANVIEN(TenNV, CMND, DiaChi, SoDienThoai, Email, MaCN) 
			VALUES (@TENNV, @CMND, @DIACHI, @SODIENTHOAI, @EMAIL, @MACN)
			COMMIT TRAN
		END
	END
GO
	
--EXEC QT_THEM_NV @TENNV = N'leyennhi', @CMND = N'123456', @DIACHI = N'1234567891', @SODIENTHOAI = '1', @EMAIL = N'leyennhi', @MACN = 1
--delete from NHANVIEN where TenNV =  N'leyennhi'

--Sửa nhân viên
CREATE OR ALTER PROCEDURE QT_SUA_NV
(
	@MANV INT,
	@TENNV NVARCHAR(50),
	@CMND NVARCHAR(15),
	@DIACHI NVARCHAR(150),
	@SODIENTHOAI NVARCHAR(15),
	@EMAIL NVARCHAR(50),
	@MACN INT
)
AS 
	BEGIN TRAN
		UPDATE NHANVIEN 
		SET TenNV = @TENNV, CMND = @CMND, DiaChi = @DIACHI, SoDienThoai = @SODIENTHOAI,	Email = @EMAIL, MaCN = @MACN
		WHERE MaNV = @MANV
	COMMIT TRAN
GO

--Xem thông tin nhân viên giao hàng.
CREATE OR ALTER PROCEDURE QT_XEM_NVGH
AS 
	BEGIN TRAN
		SELECT *
		FROM NV_GIAOHANG
	COMMIT TRAN
GO

--Thêm nhân viên giao hàng
CREATE OR ALTER PROCEDURE QT_THEM_NVGH
(
	--@MANVGH INT,
	@TENNVGH NVARCHAR(50),
	@CMND NVARCHAR(15),
	@DIACHI NVARCHAR(150),
	@SODIENTHOAI CHAR(15),
	@EMAIL NVARCHAR(50)
)
AS 
BEGIN TRAN
	IF EXISTS (SELECT * FROM NV_GIAOHANG WHERE CMND = @CMND)
	BEGIN
		RAISERROR (N'Chứng minh nhân dân đã tồn tại', 15, 1)
		ROLLBACK TRAN
	END

	ELSE 
	BEGIN
		IF EXISTS (SELECT * FROM NV_GIAOHANG WHERE SoDienThoai = @SODIENTHOAI)
		BEGIN
			RAISERROR (N'Số điện thoại đã tồn tại', 15, 1)
			ROLLBACK TRAN
		END
		ELSE 
		BEGIN
			INSERT INTO NV_GIAOHANG(TenNVGH, CMND, DiaChi, SoDienThoai, Email) 
			VALUES (@TENNVGH, @CMND, @DIACHI, @SODIENTHOAI, @EMAIL)
			COMMIT TRAN
		END
	END
GO

--EXEC QT_THEM_NVGH @TENNVGH = N'leyennhi', @CMND = N'123456', @DIACHI = N'1234567891', @SODIENTHOAI = '1', @EMAIL = N'leyennhi'
--delete from NV_GIAOHANG where TenNVGH =  N'leyennhi'

--Sửa thông tin nhân viên giao hàng
CREATE OR ALTER PROCEDURE QT_SUA_NVGH
(
	@MANVGH INT,
	@TENNVGH NVARCHAR(50),
	@CMND NVARCHAR(15),
	@DIACHI NVARCHAR(150),
	@SODIENTHOAI CHAR(15),
	@EMAIL NVARCHAR(50)
)
AS 
	BEGIN TRAN
		UPDATE NV_GIAOHANG 
		SET TenNVGH = @TENNVGH, CMND = @CMND, DiaChi = @DIACHI, SoDienThoai = @SODIENTHOAI, Email = @EMAIL
		WHERE MaNVGH = @MANVGH
	COMMIT TRAN
GO

--Xem sản phẩm.
CREATE OR ALTER PROCEDURE QT_XEM_SP
AS 
	BEGIN TRAN
		SELECT * FROM SANPHAM
	COMMIT TRAN
GO

--Thêm sản phẩm.
CREATE OR ALTER PROCEDURE QT_THEM_SP
(
	@TENSP NVARCHAR(50),
	@GIASP BIGINT,
	@SOLUONG INT,
	@MOTA NVARCHAR(150)
)
AS 
BEGIN TRAN
	IF EXISTS (SELECT * FROM SANPHAM WHERE TenSP = @TENSP)
	BEGIN
		RAISERROR (N'Sản phẩm đã tồn tại', 15, 1)
		ROLLBACK TRAN
	END

	ELSE
	BEGIN
		INSERT INTO SANPHAM (TenSP, GiaSP, SoLuong, MoTa) VALUES (@TENSP, @GIASP, @SOLUONG, @MOTA)
		COMMIT TRAN
	END
GO

--EXEC QT_THEM_SP @TENSP = N'CHOCOLATE', @GIASP = 10000, @SOLUONG = 5, @MOTA = NULL
--DELETE FROM SANPHAM WHERE TENSP = N'CHOCOLATE'

--Sửa sản phẩm.
CREATE OR ALTER PROCEDURE QT_SUA_SP
(
	@MASP INT,
	@TENSP NVARCHAR(50),
	@GIASP BIGINT,
	@SOLUONG INT,
	@MOTA NVARCHAR(150)
)
AS 
	BEGIN TRAN
		UPDATE SANPHAM SET TenSP = @TENSP, GiaSP = @GIASP, SoLuong = @SOLUONG, MoTa = @MOTA
		WHERE MaSP = @MASP
	COMMIT TRAN
GO

--Xem chi nhánh.
CREATE OR ALTER PROCEDURE QT_XEM_CN
AS 
	BEGIN TRAN
		SELECT * FROM CHINHANH
	COMMIT TRAN
GO

--Thêm chi nhánh
CREATE OR ALTER PROCEDURE QT_THEM_CN
(
	@DIACHICN NVARCHAR(150),
	@SODIENTHOAI CHAR(15)
)
AS 
BEGIN TRAN
	IF EXISTS (SELECT * FROM CHINHANH WHERE SoDienThoai = @SODIENTHOAI)
	BEGIN
		RAISERROR (N'Số điện thoại đã tồn tại', 15, 1)
		ROLLBACK TRAN
	END

	ELSE
	BEGIN
		INSERT INTO CHINHANH(DiaChiCN, SoDienThoai) VALUES (@DIACHICN, @SODIENTHOAI)
		COMMIT TRAN
	END
GO	

--EXEC QT_THEM_CN @DIACHICN = N'123 HO CHI MINH', @SODIENTHOAI = '0123456789'
--DELETE FROM CHINHANH WHERE SODIENTHOAI = '0123456789'

--Sửa chi nhánh
CREATE OR ALTER PROCEDURE QT_SUA_CN
(
	@MACN INT,
	@DIACHICN NVARCHAR(150),
	@SODIENTHOAI CHAR(15)
)
AS 
	BEGIN TRAN
		UPDATE CHINHANH 
		SET DiaChiCN = @DIACHICN, SoDienThoai = @SODIENTHOAI
		WHERE MaCN = @MACN
	COMMIT TRAN
GO

--Xem nhà cung cấp.
CREATE OR ALTER PROCEDURE QT_XEM_NCC
AS 
	BEGIN TRAN
		SELECT * FROM NHACUNGCAP
	COMMIT TRAN
GO

--Thêm nhà cung cấp
CREATE OR ALTER PROCEDURE QT_THEM_NCC
(
	@TENNCC NVARCHAR(50),
	@DIACHINCC NVARCHAR(150),
	@SODIENTHOAI CHAR(15)
)
AS 
	BEGIN TRAN
	IF EXISTS (SELECT * FROM NHACUNGCAP WHERE SoDienThoai = @SODIENTHOAI)
	BEGIN
		RAISERROR (N'Số điện thoại đã tồn tại', 15, 1)
		ROLLBACK TRAN
	END

	ELSE
	BEGIN
		INSERT INTO NHACUNGCAP(TenNCC, DiaChiNCC, SoDienThoai) VALUES (@TENNCC, @DIACHINCC, @SODIENTHOAI)
		COMMIT TRAN
	END
GO

--EXEC QT_THEM_NCC @TENNCC = N'LEYENNHI', @DIACHINCC = N'123 HO CHI MINH', @SODIENTHOAI = '0123456789'
--DELETE FROM NHACUNGCAP WHERE SODIENTHOAI = '0123456789'
	
--Sửa nhà cung cấp
CREATE OR ALTER PROCEDURE QT_SUA_NCC
(
	@MANCC INT,
	@TENNCC NVARCHAR(50),
	@DIACHINCC NVARCHAR(150),
	@SODIENTHOAI CHAR(15)
)
AS 
	BEGIN TRAN
		UPDATE NHACUNGCAP 
		SET TenNCC = @TENNCC, DiaChiNCC = @DIACHINCC, SoDienThoai = @SODIENTHOAI
		WHERE MaNCC = @MANCC
	COMMIT TRAN
GO

--Xem phiếu đặt hàng.
CREATE OR ALTER PROCEDURE QT_XEM_PHIEU_DH
AS 
	BEGIN TRAN
		SELECT * FROM PHIEUDATHANG
	COMMIT TRAN
GO

--Thêm chi tiết phiếu đặt hàng
CREATE OR ALTER PROCEDURE QT_THEM_CT_PHIEU_DH
(
	@MAPDH INT,
	@MASP NVARCHAR(10),
	@SOLUONG INT,
	@GIA BIGINT
)
AS
	BEGIN TRAN
		INSERT INTO CT_PHIEUDATHANG  VALUES	(@MAPDH,@MASP,@SOLUONG,@GIA)
		
		SELECT * FROM CT_PHIEUDATHANG WHERE MaPDH = @MAPDH
	COMMIT TRAN
GO

--Thêm phiếu đặt hàng
CREATE OR ALTER PROCEDURE QT_THEM_PHIEU_DH
(
	@NGAYDATHANG DATE,
	@MANCC INT
)
AS 
	BEGIN TRAN
		DECLARE @MAPDH TABLE (PDH INT)
		INSERT INTO PHIEUDATHANG(NgayDatHang, MaNCC)
		OUTPUT inserted.MaPDH into @MAPDH
		VALUES (@NGAYDATHANG,@MANCC)		
		(SELECT PDH FROM @MAPDH)
	COMMIT TRAN
GO

--Xem hình thức thanh toán.
CREATE OR ALTER PROCEDURE QT_XEM_HTTT
AS 
	BEGIN TRAN
		SELECT * FROM HTTHANHTOAN
	COMMIT TRAN
GO

--Thêm hình thức thanh toán.
CREATE OR ALTER PROCEDURE QT_THEM_HTTT
(
	@TENHTTT NVARCHAR(50)
)
AS 
	BEGIN TRAN
	IF EXISTS (SELECT * FROM HTTHANHTOAN WHERE TenHTTT = @TENHTTT)
	BEGIN
		RAISERROR (N'Hình thức thanh toán đã tồn tại', 15, 1)
		ROLLBACK TRAN
	END

	ELSE
	BEGIN
		INSERT INTO HTTHANHTOAN(TenHTTT) VALUES(@TENHTTT)
		COMMIT TRAN
	END
GO
	
--EXEC QT_THEM_HTTT @TENHTTT = N'leyennhi'
--delete from HTTHANHTOAN where TENHTTT = N'leyennhi'

--Sửa hình thức thanh toán.
CREATE OR ALTER PROCEDURE QT_SUA_HTTT
(
	@MAHTTT INT,
	@TENHTTT NVARCHAR(50)
)
AS 
	BEGIN TRAN
		UPDATE HTTHANHTOAN SET TenHTTT = @TENHTTT WHERE MaHTTT = @MAHTTT			
	COMMIT TRAN
GO

--Xem khách hàng.
CREATE OR ALTER PROCEDURE QT_XEM_KH
AS 
	BEGIN TRAN
		SELECT * FROM KHACHHANG
	COMMIT TRAN
GO

--Kiểm tra số lượng tồn sản phẩm.
CREATE OR ALTER PROCEDURE QT_KIEM_TRA_SL
(
	@SOLUONG INT
)
AS 
	BEGIN TRAN
		SELECT * FROM SANPHAM WHERE SoLuong < @SOLUONG 
	COMMIT TRAN
GO
